version: '3.8' # specify docker-compose version

# Define the services/containers to be run
services:
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend 
      
  mongodb: 
    image: mongo 
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend   
    
  api:
    image: hantsy/spring-reactive-jwt-sample-server
    environment:
      - "SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/blog"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - backend      
 
volumes:
  mongodata:  
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./data  

networks:
  frontend:
  backend: