name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: ' Good job. Thanks for opening your first issue.'
        pr-message: 'Thanks for sending your prs. It is awesome.'
